### ISSUE TITLE
required model changes to use MySQL DB backend

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#100]
**Reporter: martin.paces
Date: 2011/12/16 13:30**

In order to use MySQL backend (InnoDB engine) following changes must done to the EOxServer's DJango DB model: 

1) unique CharField max 255 characters (current model uses 256 characters)

Although this restriction applies to unique identifiers only, I suggest that those non-unique might be changed to 255 as well to have single a limit applied consistently.

manage.py syncdb error: 

```
Error: One or more models did not validate:
core.implementation: "impl_id": CharField cannot have a "max_length" greater than 255 when using "unique=True".
coverages.coveragerecord: "coverage_id": CharField cannot have a "max_length" greater than 255 when using "unique=True".
coverages.rectifieddatasetrecord: "eo_id": CharField cannot have a "max_length" greater than 255 when using "unique=True".
coverages.referenceabledatasetrecord: "eo_id": CharField cannot have a "max_length" greater than 255 when using "unique=True".
coverages.rectifiedstitchedmosaicrecord: "eo_id": CharField cannot have a "max_length" greater than 255 when using "unique=True".
coverages.datasetseriesrecord: "eo_id": CharField cannot have a "max_length" greater than 255 when using "unique=True".
```

2) eoxserver.resources.coverages.models.DataSource.search_pattern CharField too long 

I don't really understand this bug. The MySQL binding complaints that the field is too long (original size is 1024) and that it can be max. 1000 characters. After sever trials I found out that the max. length of that field which can be applied is 332. If set to 333 or larger the error is triggered.     

manage.py syncdb gives me following errror: 

```
...
Creating table coverages_datasource
Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    execute_manager(settings)
  File "/usr/lib/pymodules/python2.6/django/core/management/__init__.py", line 438, in execute_manager
    utility.execute()
  File "/usr/lib/pymodules/python2.6/django/core/management/__init__.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 191, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 220, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/pymodules/python2.6/django/core/management/base.py", line 351, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/pymodules/python2.6/django/core/management/commands/syncdb.py", line 95, in handle_noargs
    cursor.execute(statement)
  File "/usr/lib/pymodules/python2.6/django/db/backends/util.py", line 15, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/pymodules/python2.6/django/db/backends/mysql/base.py", line 86, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/pymodules/python2.6/MySQLdb/cursors.py", line 166, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/pymodules/python2.6/MySQLdb/connections.py", line 35, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 1000 bytes')
```

Once these two issues are fixed, the DB initialization passes and EOxServer seems to be working correctly.

**Comment by constantinius** [comment]
MySQL is not actively supported by EOxServer. It is highly recommended to use PostgreSQL instead.
