### ISSUE TITLE
WCS 2.0 rectified coverage  scaleAxes bug

### ISSUE THREAD

**Issue by pacesm** [EOxServer/eoxserver#356]
There is a bug in the axis scaling part of the renderer:

```
Traceback (most recent call last):
  File "/usr/local/eoxserver/eoxserver/services/views.py", line 68, in ows
    result = handler.handle(request)
  File "/usr/local/eoxserver/eoxserver/services/ows/wcs/basehandlers.py", line 267, in handle
    result_set = renderer.render(params)
  File "/usr/local/eoxserver/eoxserver/services/mapserver/wcs/coverage_renderer.py", line 164, in render
    self.translate_params(params, range_type)
  File "/usr/local/eoxserver/eoxserver/contrib/mapserver.py", line 206, in create_request
    for key, value in values:
  File "/usr/local/eoxserver/eoxserver/services/mapserver/wcs/coverage_renderer.py", line 257, in translate_params
    for scale in scaleaxes
  File "/usr/local/eoxserver/eoxserver/services/mapserver/wcs/coverage_renderer.py", line 257, in <genexpr>
    for scale in scaleaxes
AttributeError: 'ScaleAxis' object has no attribute 'value'
```

The `ScaleAxis` has no `value` property. The `scale` property should be used instead.

Since all the tests are passing I assume a new test case covering the `scaleAxes` WCS requests should be added too.

**Comment by pacesm** [comment]
The bug is fixed but the tests are still missing.
