### ISSUE TITLE
DSEO broken in PRISM

### ISSUE THREAD

**Issue by Schpidi** [EOxServer/eoxserver#400]
DSEO links are included in OpenSearch responses but are broken in the PRISM context. I suspect because of Object Storage usage.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
  File "/usr/local/lib/python2.7/dist-packages/zipstream/__init__.py", line 182, in __iter__
    for data in self.__write(**kwargs):
  File "/usr/local/lib/python2.7/dist-packages/zipstream/__init__.py", line 241, in __write
    st = os.stat(filename)
OSError: [Errno 2] No such file or directory: '...'
```

**Comment by constantinius** [comment]
Fixed with cb27bc44
